// <auto-generated />
using System;
using JoaoDeBarro.Receivables.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoaoDeBarro.Receivables.Infrastructure.Migrations
{
    [DbContext(typeof(ReceivableContext))]
    [Migration("20260127010719_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JoaoDeBarro.Receivables.Domain.Receivable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("InvoiceIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ServiceOrderNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("_amountReceived")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AmountReceived");

                    b.Property<decimal>("_grossAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GrossAmount");

                    b.Property<decimal>("_issAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("IssAmount");

                    b.HasKey("Id");

                    b.HasIndex("CustomerName");

                    b.HasIndex("DueDate");

                    b.ToTable("Receivables", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
