FROM node:22-alpine AS build
WORKDIR /app
ARG BUILD_CONFIGURATION=docker

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build -- --configuration ${BUILD_CONFIGURATION}

FROM nginx:1.27-alpine AS final
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
